---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: centos7
  #   image: centos:7
  - name: ubuntu1804
    image: ubuntu:18.04
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # It's not necessarily now
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    # It's not necessarily now
    # - idempotence
    # It's not necessarily now
    # - side_effect 
    - verify
    - destroy