---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: centos7
  #   image: centos:7
  - name: ubuntu1804
    image: ubuntu:18.04
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy